core/exchange/urls.py
""" Project URLS """
from django.conf import settings
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control
from django.views.generic.base import RedirectView, TemplateView
from rest_framework import routers

from exchange.accounting.views import deposit_system_bank_account
from exchange.accounts.views import anti_phishing as anti_phishing_views
from exchange.accounts.views import auth as auth_views
from exchange.accounts.views import captcha as captcha_views
from exchange.accounts.views import internal as internal_accounts
from exchange.accounts.views import merge as merge_views
from exchange.accounts.views import otp as otp_views
from exchange.accounts.views import profile as profile_views
from exchange.accounts.views import referral as referral_views
from exchange.accounts.views import userplan as userplan_views
from exchange.accounts.views.restriction import UserRestrictionView
from exchange.android import views as android_views
from exchange.apikey import views as apikey
from exchange.asset_backed_credit.api import views as abc_views
from exchange.base import views as base_views
from exchange.blockchain import views as blockchain
from exchange.captcha.views import captcha_image as captcha_image_views
from exchange.charts import urls as charts_urls
from exchange.corporate_banking.api import views as corporate_banking
from exchange.credit import views as credit
from exchange.crm import views as crms
from exchange.direct_debit.api import views as direct_debit
from exchange.earn import views as earn
from exchange.features.views import get_request_status, register_request_in_queue
from exchange.gift import views as gift
from exchange.gift.postal_order_views import get_padro_province_cities, get_padro_provinces
from exchange.margin import views as margin
from exchange.market import coinmarketcap
from exchange.market import udf as market_udf
from exchange.market import views as market
from exchange.marketing.api.views import referral
from exchange.marketing.api.views import user_suggestion as marketing
from exchange.marketing.api.views.campaign import (
    CampaignInfoRequestView,
    CampaignJoinRequestView,
    CampaignRewardCapacityView,
    CampaignRewardRequestView,
)
from exchange.marketing.api.views.otp import CampaignOTPRequestView, CampaignOTPVerifyView
from exchange.metrics import views as metrics
from exchange.notification.api import views as notification
from exchange.oauth.api import views as oauth
from exchange.oauth.api.services import views as oauth_services
from exchange.pool import views as pool
from exchange.portfolio.views import (
    get_daily_total_balance,
    last_month_total_profit,
    last_week_daily_profit,
    last_week_daily_total_profit,
)
from exchange.pricealert import views as pricealert
from exchange.promotions import views as promotions
from exchange.recovery import views as recovery
from exchange.redeem import views as redeem
from exchange.report.views import status as status_report
from exchange.report.views import views as report
from exchange.security import views as security
from exchange.security.views.address_book import (
    DeleteAddressBookView,
    ListCreateAddressBookView,
    activate_whitelist,
    deactivate_whitelist,
)
from exchange.shetab import urls as shetab_urls
from exchange.shetab import views as shetab
from exchange.socialtrade import views as social_trade
from exchange.staking import views as staking
from exchange.support import views as support
from exchange.support.views import get_next_call_reason_url
from exchange.system.views import ListBotTransactionView
from exchange.ticketing import views as ticketing
from exchange.wallet import views as wallet
from exchange.wallet.internal.views import (
    internal_batch_transaction_view,
    internal_bulk_transfer_view,
    internal_list_wallets_view,
    internal_withdraw_rial_view,
)
from exchange.web_engage.api.views.discount import (
    CheckActiveUserDiscountApi,
    CreateUserDiscountApi,
    SendExternalDiscountApi,
)
from exchange.web_engage.api.views.esp import ESPDeliveryStatusApi, ESPMessageApi
from exchange.web_engage.api.views.ssp import SSPMessageApi
from exchange.ws.views import healthcheck_ws_publish, ws_status
from exchange.xchange import views as xchange

router = routers.DefaultRouter()
admin.site.site_header = 'Nobitex Admin'
admin.site.site_title = 'Nobitex Admin'
urlpatterns = [
    # Base
    path('', base_views.home),
    path('base/ntp', base_views.ntp),

    # CRM
    path('crm/news/list', crms.NewsList.as_view()),
    path('crm/news/tags/list', crms.NewsTags.as_view()),

    # Health Checks
    path('check/connectivity', base_views.connectivity),
    path('check/token', base_views.check_token),
    path('check/version', base_views.check_version),
    path('check/debug', base_views.check_debug),
    path('check/health', base_views.check_health),

    # v2
    path('v2/options', profile_views.v2_options),
    path('v2/depth/<str:symbol>', market.DepthChartAPI.as_view()),
    path('v2/orderbook', market.v2_orderbook),  # Deprecated
    path('v2/orderbook/<str:symbol>', market.OrderBookV2.as_view()),
    path('v2/trades', market.v2_trades),  # Deprecated
    path('v2/trades/<str:symbol>', market.v2_trades_get),
    path('v2/crypto-prices', market.v2_crypto_prices),
    # v3
    path('v3/orderbook/<str:symbol>', market.OrderBookV3.as_view()),

    # Market
    path('market/orders/list', market.orders_list),
    path('market/orders/open-count', market.OpenOrderCountView.as_view()),
    path('market/orders/add', market.OrderCreateView.as_view()),
    path('market/orders/batch-add', market.OrderBatchCreateView.as_view()),
    path('market/orders/estimate', market.orders_estimate),
    path('market/orders/status', market.orders_status),
    path('market/orders/cancel-old', market.orders_cancel_old),
    path('market/orders/cancel-batch', market.orders_cancel_batch),
    path('market/orders/update-status', market.orders_update_status),
    path('market/stats', market.market_stats),
    path('market/global-stats', market.market_global_stats),
    path('market/trades/list', market.trades_list),
    path('market/usd-value', market.usd_value),

    # Market Chart (UDF)
    path('market/udf/config', market_udf.udf_config),
    path('market/udf/symbols', market_udf.udf_symbols),
    path('market/udf/search', market_udf.udf_search),
    path('market/udf/history', market_udf.UDFHistory.as_view()),
    path('market/udf/time', market_udf.udf_time),
    path('market/udf/quotes', market_udf.udf_quotes),
    path('charts/storage/1.1/', include(charts_urls)),


    # Marketing
    path('marketing/suggestion-category/list', marketing.suggestion_category_list),
    path('marketing/suggestion/add', marketing.add_user_suggestion),
    path('marketing/campaign', CampaignInfoRequestView.as_view()),
    path('marketing/campaign/join', CampaignJoinRequestView.as_view()),
    path('marketing/campaign/reward', CampaignRewardRequestView.as_view()),
    path('marketing/campaign/reward/capacity', CampaignRewardCapacityView.as_view()),
    path('marketing/campaign/referral', referral.ReferralCampaign.as_view()),
    path('marketing/campaign/otp', CampaignOTPRequestView.as_view()),
    path('marketing/campaign/otp/verify', CampaignOTPVerifyView.as_view()),
    path('marketing/campaign/webengage/discount/external', SendExternalDiscountApi.as_view()),

    # Margin
    path('margin/markets/list', margin.MarginMarketListView.as_view()),
    path('margin/fee-rates', margin.MarginFeeRatesListView.as_view()),
    path('margin/orders/add', margin.MarginOrderCreateView.as_view()),
    path('margin/delegation-limit', margin.MarginDelegationLimitView.as_view()),
    path('margin/calculator/<str:mode>', margin.MarginCalculatorView.as_view()),
    path('margin/predict/<str:category>', margin.MarginPredictView.as_view()),
    path('positions/list', margin.PositionsListView.as_view()),
    path('positions/active-count', margin.ActivePositionsCountView.as_view()),
    path('positions/<int:pk>/status', margin.PositionStatusView.as_view()),
    path('positions/<int:pk>/close', margin.PositionCloseView.as_view()),
    path('positions/<int:pk>/edit-collateral/options', margin.PositionCollateralEditOptionsView.as_view()),
    path('positions/<int:pk>/edit-collateral', margin.PositionCollateralEditView.as_view()),

    # Special Tradings
    path('market/autotrade/get-options', market.autotrade_get_options),
    path('market/autotrade/set-options', market.autotrade_set_options),

    # User Profile
    path('users/preferences', profile_views.users_preferences),
    path('users/set-preference', profile_views.users_set_preference),
    path('users/profile', profile_views.users_profile),
    path('users/limitations', profile_views.users_limitations),
    path('users/profile-edit', profile_views.users_profile_edit),
    path('users/cards-add', profile_views.users_cards_add),
    path('users/cards-delete', profile_views.users_cards_delete),
    path('users/accounts-add', profile_views.users_accounts_add),
    path('users/payment-accounts-add', profile_views.users_payment_accounts_add),
    path('users/accounts-delete', profile_views.users_accounts_delete),
    path('users/verify', profile_views.users_verify),
    path('users/verify-email', profile_views.users_verify_email),
    path('users/verify-mobile', profile_views.users_verify_mobile, name='verify-mobile'),
    path('users/verify-phone', profile_views.users_verify_phone),
    path('users/reset-verification', profile_views.users_reset_verification),
    path('users/verification/status', profile_views.verification_status),
    path('users/upload-file', profile_views.upload_file),
    path('users/set-national-serial-number', profile_views.users_national_serial_add),

core/exchange/asset_backed_credit/models/report.py
from django.db import models
from django.db.models import UniqueConstraint

from exchange.asset_backed_credit.models import Service
from exchange.base.storages import get_private_s3_storage


class CreditReport(models.Model):
    class Status(models.IntegerChoices):
        CREATED = 0
        COMPLETED = 2

    class Type(models.IntegerChoices):
        ALL = 0
        LOCK = 1
        UNLOCK = 2
        SETTLEMENT = 3
        SETTLEMENT_MISMATCH = 4

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=Status.choices, default=Status.CREATED)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    type = models.IntegerField(choices=Type.choices, default=Type.ALL)


class ReportAttachment(models.Model):
    class AttachmentType(models.IntegerChoices):
        LOCK = 1
        UNLOCK = 2
        SETTLEMENT = 3
        SETTLEMENT_MISMATCH = 4

    report = models.ForeignKey(CreditReport, on_delete=models.CASCADE, related_name='attachments')
    attachment_type = models.IntegerField(choices=AttachmentType.choices)
    file = models.FileField(upload_to='abc_report', storage=get_private_s3_storage)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = (
            UniqueConstraint(
                fields=('report', 'attachment_type'),
                name='unique_per_report_attachment_type',
            ),
        )

core/exchange/audit/models.py
from decimal import Decimal

from django.db import models
from django.utils.timezone import now
from model_utils import Choices

from exchange.base.models import Currencies, Exchange
from exchange.wallet.models import WithdrawRequest


class ExternalWallet(models.Model):
    TYPES = Choices(
        (0, 'unknown', 'Unknown'),
        (1, 'binance', 'Binance'),
        (2, 'hot', 'Hot Wallet'),
        (3, 'cold', 'Cold Wallet'),
    )

    name = models.CharField(max_length=100, blank=True, unique=True)
    currency = models.IntegerField(choices=Currencies, verbose_name='رمزارز')
    tp = models.IntegerField(choices=TYPES, default=TYPES.unknown, verbose_name='نوع')
    address = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = 'External Wallet'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ExternalWithdraw(models.Model):
    TYPES = Choices(
        (0, 'new', 'New'),
        (1, 'user_withdraw', 'UserWithdraw'),
        (2, 'unknown', 'Unknown'),
    )

    created_at = models.DateTimeField(default=now)
    tp = models.IntegerField(choices=TYPES, default=TYPES.new, verbose_name='نوع برداشت')
    user_withdraw = models.ForeignKey(WithdrawRequest, null=True, blank=True, on_delete=models.SET_NULL)

    source = models.ForeignKey(ExternalWallet, related_name='withdraws', on_delete=models.CASCADE)
    destination = models.CharField(max_length=100, blank=True, default='')
    tx_hash = models.CharField(max_length=100, blank=True, default='')
    tag = models.CharField(max_length=100, blank=True, null=True, verbose_name='تگ')
    currency = models.IntegerField(choices=Currencies, default=0, verbose_name='رمزارز')
    amount = models.DecimalField(max_digits=20, decimal_places=10, default=Decimal('0'), verbose_name='مقدار برداشت')

    class Meta:
        verbose_name = 'رکورد برداشت'
        verbose_name_plural = verbose_name
        unique_together = ['tx_hash', 'destination']

core/exchange/report/forms.py
from django import forms


class ControlPanelForm(forms.Form):
    module_matching_engine = forms.ChoiceField(label='موتور معاملات (Matcher)', choices=[
        ('enabled', 'فعال'),
        ('disabled', 'غیرفعال'),
    ])
    module_autotrader_engine = forms.ChoiceField(label='موتور معاملات خوکار (Autotrading)', choices=[
        ('enabled', 'فعال'),
        ('disabled', 'غیرفعال'),
    ])
    module_withdraw_processing = forms.ChoiceField(label='پردازش خودکار درخواست‌های برداشت', choices=[
        ('enabled', 'فعال'),
        ('disabled', 'غیرفعال'),
    ])
    module_deposit_processing = forms.ChoiceField(label='تشخیص واریزهای رمزارزی', choices=[
        ('enabled', 'فعال'),
        ('activeusers', 'کاربران آنلاین'),
        ('onrequest', 'به درخواست کاربر'),
        ('disabled', 'غیرفعال'),
    ])

core/exchange/report/views/status.py
import datetime

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from django.shortcuts import render
from django.utils.timezone import now

from exchange.base.models import AVAILABLE_CURRENCIES, RIAL, XCHANGE_CURRENCIES, get_currency_codename
from exchange.shetab.models import ShetabDeposit
from exchange.wallet.models import ConfirmedWalletDeposit, WithdrawRequest


def access_status_reports(user):
    if not user.is_staff:
        return False
    if user.is_superuser:
        return True
    return user.groups.filter(name__in=['support', 'developer']).exists()


@user_passes_test(access_status_reports)
def overview(request):
    reports = {}
    date_filter = Q(created_at__gt=now() - datetime.timedelta(hours=24))
    if settings.DEBUG:
        date_filter = Q()
    for currency in AVAILABLE_CURRENCIES + XCHANGE_CURRENCIES:
        if currency == RIAL:
            deposits = ShetabDeposit.objects.filter(
                date_filter,
                transaction__isnull=False,
            ).select_related('user').order_by('-amount')[:20]
        else:
            # TODO: Are these select_related necessary?
            deposits = ConfirmedWalletDeposit.objects.filter(
                date_filter,
                address__currency=currency,
                confirmed=True,
                validated=True,
            ).select_related('address', '_wallet', 'address__wallet', 'address__wallet__user').order_by('-amount')[:20]
        withdraws = WithdrawRequest.objects.filter(
            date_filter,
            wallet__currency=currency,
            status__gte=WithdrawRequest.STATUS.verified,
        ).select_related('wallet', 'wallet__user').order_by('-amount')[:20]
        reports[get_currency_codename(currency).upper()] = {
            'deposits': deposits,
            'withdraws': withdraws,
            'users': [],
        }
    return render(request, 'status/overview.html', {
        'reports': reports,
    })

core/exchange/report/templates/report/control_panel.html
{% extends 'ebase.html' %}
{% load bootstrap4 %}

{% block content %}
    <style>
        .form-group {
            margin: 2rem 0;
        }
    </style>

    <div class="jumbotron text-center">
        <h1>پنل مدیریت</h1>
        <p>مدیریت اجزای کارکردی نوبیتکس</p>
    </div>

    <h4 class="text-right"></h4>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">ذخیره</button>
        {% endbuttons %}
    </form>
{% endblock %}

core/exchange/report/templates/report/wallets.html
{% extends 'ebase.html' %}
{% load nobitex %}

{% block content %}
<style>
.wallets-section {min-height: 300px; position: relative; margin-top: 3rem;}
.wallets-section h5 {position: absolute; top: 8px; right: 1px;}
</style>

<div class="jumbotron text-center">
  <h1>کیف پول‌ها</h1>
</div>

<h5 class="text-right">مجموع موجودی‌ها</h5>
<table class="table table-striped table-sm text-right rtl-div">
    <thead class="thead-dark">
        <tr>
            <th>نوع کیف پول</th>
            {% for c in currencies %}
            <th>{{ c }}</th>
            {% endfor %}
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><span class="badge badge-pill badge-danger">گرم</span></td>
            {% for balance in hot_balances %}
            <td>{{ balance|floatformat:4 }}</td>
            {% endfor %}
            <td>
              <form action="/bitex/wallets/update-balance" method="POST">
                <input type="hidden" name="action" value="update-hot">
                <input type="hidden" name="wallet" value="0">
                <button type="submit" class="btn btn-info btn-sm">↺</button>
              </form>
            </td>
        </tr>
        <tr>
            <td><span class="badge badge-pill badge-info">سرد</span></td>
            {% for balance in cold_balances %}
            <td>{{ balance|floatformat:4 }}</td>
            {% endfor %}
            <td>
              <form action="/bitex/wallets/update-balance" method="POST">
                <input type="hidden" name="action" value="update-cold">
                <input type="hidden" name="wallet" value="0">
                <button type="submit" class="btn btn-info btn-sm">↺</button>
              </form>
            </td>
        </tr>
        <tr>
            <td><span class="badge badge-pill badge-info">سرد سیستمی</span></td>
            {% for balance in system_cold_balances %}
            <td>{{ balance|floatformat:4 }}</td>
            {% endfor %}
            <td>
              <form action="/bitex/wallets/update-balance" method="POST">
                <input type="hidden" name="action" value="update-cold-system">
                <input type="hidden" name="wallet" value="0">
                <button type="submit" class="btn btn-info btn-sm">↺</button>
              </form>
            </td>
        </tr>
        <tr>
            <td><span class="badge badge-pill badge-dark">مجموع</span></td>
            {% for balance in sum_balances %}
            <td>{{ balance|floatformat:4 }}</td>
            {% endfor %}
        </tr>
    </tbody>
</table>

<h5 class="mt-5 text-right"><span class="badge badge-pill badge-danger">گرم</span> کیف پول‌های</h5>
<table class="table table-striped table-sm text-right rtl-div">
    <thead class="thead-dark">
        <tr>
            <th>ردیف</th>
            <th>آدرس</th>
            <th>رمزارز</th>
            <th>موجودی</th>
            <th>ارزش</th>
            <th>به‌روزرسانی</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for wallet in hot_wallets %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ wallet.address }}</td>
            <td>{{ wallet.currency_display }}</td>
            <td>{{ wallet.current_balance|moneyformat:wallet.currency }}</td>
            <td>${{ wallet.balance_value|moneyformat:13 }}</td>
            <td>{{ wallet.last_update_check }}</td>
            <td>
              <form action="/bitex/wallets/update-balance" method="POST">
                <input type="hidden" name="action" value="update-hot">
                <input type="hidden" name="wallet" value="{{ wallet.pk }}">
                <button type="submit" class="btn btn-info btn-sm">↺</button>
              </form>
            </td>
        </tr>
        {% empty %}
        <tr>
          <td class="text-center" colspan="6">کیف پولی ثبت نشده است</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h5 class="mt-5 text-right"><span class="badge badge-pill badge-info">سرد سیستمی</span> کیف پول‌های</h5>
<table class="table table-striped table-sm text-right rtl-div">
    <thead class="thead-dark">
        <tr>
            <th>شناسه</th>
            <th>آدرس</th>
            <th>رمزارز</th>
            <th>موجودی</th>
            <th>به‌روزرسانی</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for address in system_cold_addresses %}
        <tr>
            <th>{{ address.pk }}</th>
            <td>{{ address.address }}</td>
            <td>{{ address.currency_display }}</td>
            <td>{{ address.current_balance|moneyformat:address.currency }}</td>
            <td>{{ address.last_update_check }}</td>
            <td>
              <form action="/bitex/wallets/update-balance" method="POST">
                <input type="hidden" name="action" value="update-cold-system">
                <input type="hidden" name="wallet" value="{{ address.pk }}">
                <button type="submit" class="btn btn-info btn-sm">↺</button>
              </form>
            </td>
        </tr>
        {% empty %}
        <tr>
          <td class="text-center" colspan="6">کیف پولی ثبت نشده است</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="wallets-section">
<h5 class="text-right"><span class="badge badge-pill badge-info">سرد</span> کیف پول‌های</h5>
<ul class="nav nav-tabs" id="cold-wallets-currency" role="tablist">
  {% for c in currencies %}
  <li class="nav-item">
    <a class="nav-link {% if forloop.first %}active{% endif %}" id="cold-wallets-currency-{{ c }}" data-toggle="pill" href="#cold-wallets-{{ forloop.counter }}" role="tab" aria-controls="pills-home" aria-selected="true">{{ c }}</a>
  </li>
  {% endfor %}
</ul>
<div class="tab-content" id="cold-wallets-tabs">
  {% for wallets in cold_wallets %}
  <div class="tab-pane fade show {% if forloop.first %}active{% endif %}" id="cold-wallets-{{ forloop.counter }}" role="tabpanel" aria-labelledby="pills-home-tab">
    <table class="table table-striped table-sm text-right rtl-div">
      <thead class="thead-dark">
          <tr>
              <th>شناسه</th>
              <th>آدرس</th>
              <th>کاربر</th>
              <th>رمزارز</th>
              <th>موجودی</th>
              <th>به‌روزرسانی</th>
              <th></th>
          </tr>
      </thead>
      <tbody>
          {% for wallet in wallets %}
          <tr>
              <th>{{ wallet.pk }}</th>
              <td>{{ wallet.address }}</td>
              <td>{{ wallet.wallet.user }}</td>
              <td>{{ wallet.wallet.get_currency_display }}</td>
              <td>{{ wallet.current_balance|moneyformat:wallet.wallet.currency }}</td>
              <td>{{ wallet.last_update_check }}</td>
              <td>
                <form action="/bitex/wallets/update-balance" method="POST">
                  <input type="hidden" name="action" value="update-cold">
                  <input type="hidden" name="wallet" value="{{ wallet.pk }}">
                  <button type="submit" class="btn btn-info btn-sm">↺</button>
                </form>
              </td>
          </tr>
          {% empty %}
          <tr>
            <td class="text-center" colspan="7">کیف پولی ثبت نشده است</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
  {% endfor %}
</div>
</div>

{% endblock %}